CC=gcc
CFLAGS=-c -Wall

all: myshell factorial plusTwo minusTwo

myshell: myshell.c
		$(CC) myshell.c -o myshell

factorial: factorial.c
		$(CC) factorial.c -o factorial

plusTwo: plusTwo.c
		$(CC) plusTwo.c -o plusTwo

minusTwo: minusTwo.c
		$(CC) minusTwo.c -o minusTwo

clean:
	rm -rf *o myshell	
